server:
    port: 8080
    servlet:
        context-path: /mymangaapp

spring:
    application:
        name: mymangaapp
    datasource:
        url: ${DB_URL}
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        username: root
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
