server:
    port: 8080
    servlet:
        context-path: /mymangaapp

spring:
    application:
        name: mymangaapp
    datasource:
        url: ${DB_URL}
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        username: root
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false

jwt:
    signer-key: ${SIGNER_KEY}
    access-token-validity-in-seconds: ${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
    refreshable-duration-in-seconds: ${REFRESHABLE_DURATION_IN_SECONDS}


app:
    init:
        admin:
            password: ${INIT_ADMIN_PASSWORD}
        user1:
            password: ${INIT_USER1_PASSWORD}
        user2:
            password: ${INIT_USER2_PASSWORD}
        user3:
            password: ${INIT_USER3_PASSWORD}
